// Generated from the approved Pakistan Sweets menu spreadsheet.
export interface ProductVariation { label: string; price: number; }
export interface Product { id: number; en: string; ar: string; price: number; img: string; cat: string; sub: string; variations?: ProductVariation[]; }
export const PRODUCTS: Product[] = [
  { id: 200000, en: "Khameeri Roti", ar: "خمة خبز", price: 1, img: "/products/11490.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200001, en: "Desi Roti", ar: "نخالة نان", price: 1, img: "/products/11493.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200002, en: "Kulcha Naan", ar: "عادي نان", price: 3, img: "/products/11496.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200003, en: "Roghni Naan", ar: "روغني نان", price: 4, img: "/products/11499.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200004, en: "Kalwanji Naan", ar: "حبة البركة نان", price: 4, img: "/products/11502.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200005, en: "Garlic Naan", ar: "ثوم نان", price: 4, img: "/products/11505.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200006, en: "Nutella Naan", ar: "نوتيلا نان", price: 8, img: "/products/11508.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200007, en: "Chicken Naan", ar: "دجاج نان", price: 10, img: "/products/11511.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200008, en: "Qeema Naan", ar: "كي نان", price: 12, img: "/products/11514.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200009, en: "Pizza Naan", ar: "بيتزا نان", price: 12, img: "/products/11517.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200010, en: "Aloo Naan", ar: "بطاطس نان", price: 6, img: "/products/11520.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200011, en: "Cheese Naan", ar: "ج نان", price: 6, img: "/products/11523.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200012, en: "Tawa Pratha", ar: "تاوا باراثا", price: 2, img: "/products/11526.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200013, en: "Desi Ghee Pratha", ar: "باراثا السمن الهندي", price: 3, img: "/products/11529.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200014, en: "Aloo Pratha", ar: "براتا البطاطس", price: 5, img: "/products/11532.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200015, en: "Qeema Pratha", ar: "كي باراثا", price: 12, img: "/products/11536.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200016, en: "Chicken Pratha", ar: "براتا دجاج", price: 10, img: "/products/11539.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200017, en: "Chicken Cheese Pratha", ar: "براتا دجاج بالجبنة", price: 12, img: "/products/11542.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200018, en: "Cheeni Pratha", ar: "براثا حلوة", price: 3, img: "/products/11546.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200019, en: "Mooli Pratha", ar: "مولى براثا", price: 6, img: "/products/11549.jpg", cat: "tandoor", sub: "tandoor" },
  { id: 200020, en: "Haleem Chicken", ar: "دجاج حليم", price: 9, img: "/products/11602.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200021, en: "Chicken Biryani", ar: "بريا دجاج", price: 13, img: "/products/11605.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200022, en: "Aloo Biryani", ar: "بريا البطاطس", price: 9, img: "/products/11608.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200023, en: "Daal Chawal", ar: "أرز العدس", price: 9, img: "/products/11611.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200024, en: "Paya", ar: "خبب", price: 24, img: "/products/11614.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200025, en: "Nihari Beef", ar: "لحم نهاري", price: 18, img: "/products/11617.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200026, en: "Channa Dal", ar: "حمص عدس", price: 8, img: "/products/11620.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200027, en: "Maash Dal", ar: "ماش دال", price: 8, img: "/products/11625.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200028, en: "Aloo Qeema", ar: "بطاطا كي", price: 15, img: "/products/11628.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200029, en: "Bhindi", ar: "البامية", price: 11, img: "/products/11631.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200030, en: "Mix Vegetable", ar: "مزيج الخضار", price: 8, img: "/products/11636.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200031, en: "Rajma", ar: "لى حبوب الك", price: 12, img: "/products/11639.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200032, en: "Zeera Rice", ar: "جا رايس", price: 5, img: "/products/11642.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200033, en: "Rice", ar: "أرز", price: 4, img: "/products/11645.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200034, en: "Anday Wala Burger", ar: "برجر شامي بيض", price: 9, img: "/products/11648.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200035, en: "Salad", ar: "سلطة", price: 4, img: "/products/11668.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200036, en: "Kachumber Salad", ar: "سلطة الكاشومبر", price: 4, img: "/products/11671.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200037, en: "Chicken Yakhni Pulao", ar: "دجاج ياخني بولاو", price: 16, img: "/products/11674.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200038, en: "Gur Wale Chawal", ar: "أرز جاجري", price: 8, img: "/products/11677.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200039, en: "Mutton Qorma", ar: "لحم ضأن كورما", price: 18, img: "/products/11680.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200040, en: "Fry Egg", ar: "بيض مقلي", price: 4, img: "/products/11683.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200041, en: "Omelette", ar: "عجة", price: 4, img: "/products/11688.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200042, en: "Egg Burji", ar: "شكشوكة باكستانية", price: 5, img: "/products/11691.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200043, en: "Palak Aloo", ar: "سبانخ البطاطس", price: 10, img: "/products/11694.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200044, en: "Aloo Gobi", ar: "بطاطس القرنبيط", price: 8, img: "/products/11697.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200045, en: "Palak Paneer", ar: "بان السبانخ", price: 16, img: "/products/11700.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200046, en: "Chana Chawal", ar: "أرز الحمص", price: 8, img: "/products/11703.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200047, en: "Channa Special", ar: "الحمص خاص", price: 8, img: "/products/11706.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200048, en: "Chana Chicken", ar: "دجاج الحمص", price: 12, img: "/products/11709.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200049, en: "Matar Qeema", ar: "بازلاء كي", price: 14, img: "/products/11713.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200050, en: "Shimla Qeema", ar: "كي الفلفل الحلو", price: 14, img: "/images/restaurant.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200051, en: "Chicken Karahi", ar: "دجاج كاراهي", price: 22, img: "/products/11539.jpg", cat: "restaurant-items", sub: "restaurant-items", variations: [{ label: "½ KG", price: 22 }, { label: "1 KG", price: 40 }] },
  { id: 200052, en: "Chicken Masala Fry", ar: "لي دجاج ماسالا مق", price: 14, img: "/products/11720.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200053, en: "Punjabi Curry Pakora", ar: "باكورا الكاري البنجابية", price: 8, img: "/products/11724.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200054, en: "Anda Chawal", ar: "أرز البيض", price: 6, img: "/products/11727.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200055, en: "Mutton Kali Mirch Yakhni", ar: "لحم ضأن بالفلفل الأسود ياخني", price: 14, img: "/products/11730.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200056, en: "Chicken Pratha Roll", ar: "رول براتا دجاج", price: 9, img: "/products/11539.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200057, en: "Chicken Achari Pratha Roll", ar: "لفائف دجاج أشاري براتا", price: 10, img: "/products/11736.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200058, en: "Chicken Achari", ar: "دجاج أشاري", price: 12, img: "/products/11736.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200059, en: "Mutton Achari", ar: "لحم الضأن أشاري", price: 16, img: "/products/11739.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200060, en: "Daal Makhni", ar: "دال ماخني", price: 9, img: "/products/11742.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200061, en: "French Fries", ar: "بطاطس مقلية", price: 7, img: "/products/11746.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200062, en: "Aloo Gosht", ar: "بطاطا لحم الضأن", price: 15, img: "/products/11749.jpg", cat: "restaurant-items", sub: "restaurant-items" },
  { id: 200063, en: "Signature Red Sauce", ar: "صلصة حمراء", price: 4, img: "/images/restaurant.jpg", cat: "sauce", sub: "sauce" },
  { id: 200064, en: "Green Chutney", ar: "الصلصة الخضراء", price: 5, img: "/products/11653.jpg", cat: "sauce", sub: "sauce" },
  { id: 200065, en: "Sweet Apricot Sauce", ar: "صلصة المشمش الحلوة", price: 6, img: "/products/11656.jpg", cat: "sauce", sub: "sauce" },
  { id: 200066, en: "Raita Phulki", ar: "فول رايتا", price: 5, img: "/products/11659.jpg", cat: "sauce", sub: "sauce" },
  { id: 200067, en: "Boondi Raita", ar: "بوندي رايتا", price: 5, img: "/products/11662.jpg", cat: "sauce", sub: "sauce" },
  { id: 200068, en: "Mint Raita", ar: "نعناع رايتا", price: 3, img: "/products/11665.jpg", cat: "sauce", sub: "sauce" },
  { id: 200069, en: "Badaam Milk", ar: "حليب اللوز", price: 12, img: "/products/11558.jpg", cat: "drinks", sub: "drinks" },
  { id: 200070, en: "Sardai Milk", ar: "حليب سارداي", price: 12, img: "/products/11562.jpg", cat: "drinks", sub: "drinks" },
  { id: 200071, en: "Badaam Sherbat", ar: "شربات اللوز", price: 5, img: "/products/11565.jpg", cat: "drinks", sub: "drinks" },
  { id: 200072, en: "Rooh Afza Sherbat", ar: "روح أفزا شربات", price: 5, img: "/products/11568.jpg", cat: "drinks", sub: "drinks" },
  { id: 200073, en: "Shikwanji Soda", ar: "صودا الليمون", price: 8, img: "/products/11571.jpg", cat: "drinks", sub: "drinks" },
  { id: 200074, en: "Khurmani Thanda Sherbat", ar: "شربات المشمش", price: 8, img: "/products/11574.jpg", cat: "drinks", sub: "drinks" },
  { id: 200075, en: "Lassi Peda", ar: "ل بانل بان", price: 12, img: "/products/11577.jpg", cat: "drinks", sub: "drinks" },
  { id: 200076, en: "Lassi Khoya", ar: "ل حليب", price: 12, img: "/products/11581.jpg", cat: "drinks", sub: "drinks" },
  { id: 200077, en: "Lassi Sweet/Salty", ar: "ل حلو/مالح", price: 6, img: "/products/11585.jpg", cat: "drinks", sub: "drinks" },
  { id: 200078, en: "Tea Karak", ar: "شاي كرك", price: 1, img: "/products/11590.jpg", cat: "drinks", sub: "drinks" },
  { id: 200079, en: "Fresh Milk Tea", ar: "طازج حليب شاي", price: 3, img: "/products/11593.jpg", cat: "drinks", sub: "drinks" },
  { id: 200080, en: "Green Tea", ar: "الشاي الأخضر", price: 1, img: "/products/11596.jpg", cat: "drinks", sub: "drinks" },
  { id: 200081, en: "Sulemani Tea", ar: "شاي سلي", price: 1, img: "/products/11599.jpg", cat: "drinks", sub: "drinks" },
  { id: 200082, en: "Biscuits (Special) per kg", ar: "بسكويت (خاص) 1 كيلو", price: 65, img: "/products/10652.jpg", cat: "bakery", sub: "bakery" },
  { id: 200083, en: "Cake Rusk", ar: "ط الكيك 1 كيلو بقس", price: 50, img: "/products/10653.jpg", cat: "bakery", sub: "bakery" },
  { id: 200084, en: "Badaam Khtaai", ar: "بسكويت اللوز", price: 65, img: "/products/10654.jpg", cat: "bakery", sub: "bakery" },
  { id: 200085, en: "Cake Rusk (Sugar Free)", ar: "ط الكيك بقس", price: 65, img: "/products/10655.jpg", cat: "bakery", sub: "bakery" },
  { id: 200086, en: "Plain Rusk", ar: "ط عادي بقس", price: 9, img: "/products/10656.jpg", cat: "bakery", sub: "bakery" },
  { id: 200087, en: "Gol Rusk", ar: "ط مدور 250 جرام بقس", price: 9, img: "/products/10657.jpg", cat: "bakery", sub: "bakery" },
  { id: 200088, en: "Bakarkhani", ar: "بكرخا 1 كيلو", price: 50, img: "/products/10658.jpg", cat: "bakery", sub: "bakery" },
  { id: 200089, en: "Sugar Puff", ar: "معجنات السكر 1 كيلو", price: 50, img: "/products/10659.jpg", cat: "bakery", sub: "bakery" },
  { id: 200090, en: "Mix Tie Puff", ar: "معجنات تيي 1 كيلو", price: 50, img: "/products/10660.jpg", cat: "bakery", sub: "bakery" },
  { id: 200091, en: "Masala Puff", ar: "معجنات ماسالا 1 كيلو", price: 50, img: "/products/10661.jpg", cat: "bakery", sub: "bakery" },
  { id: 200092, en: "Bread (White)", ar: "بريد صغ", price: 4, img: "/products/10662.jpg", cat: "bakery", sub: "bakery", variations: [{ label: "QAR 4", price: 4 }, { label: "QAR 6", price: 6 }] },
  { id: 200093, en: "Bread (Milky)", ar: "بريد صغ حليبي", price: 4, img: "/products/10663.jpg", cat: "bakery", sub: "bakery", variations: [{ label: "QAR 4", price: 4 }, { label: "QAR 6", price: 6 }] },
  { id: 200094, en: "Brown Bread", ar: "خبز أسمر", price: 6, img: "/products/11063.jpg", cat: "bakery", sub: "bakery" },
  { id: 200095, en: "Multi Grain Bread", ar: "خبز متعدد الحبوب", price: 6, img: "/products/11067.jpg", cat: "bakery", sub: "bakery" },
  { id: 200096, en: "Sheermal Bun", ar: "مال ش", price: 4, img: "/products/11070.webp", cat: "bakery", sub: "bakery" },
  { id: 200097, en: "Biscuits (Regular) per kg", ar: "بسكويت (عادي) 1 كيلو", price: 50, img: "/images/bakery.jpg", cat: "bakery", sub: "bakery" },
  { id: 200098, en: "Uncooked Samosa", ar: "سمبوسة غير مقلية", price: 9, img: "/products/10648.jpg", cat: "bakery", sub: "frozen" },
  { id: 200099, en: "Uncooked Spring Roll", ar: "سبرنج رول غير مقلية", price: 20, img: "/products/10647.jpg", cat: "bakery", sub: "frozen" },
  { id: 200100, en: "Uncooked Cheese Samosa", ar: "سمبوسة جبنة غير مقلية", price: 10, img: "/products/10648.jpg", cat: "bakery", sub: "frozen" },
  { id: 200101, en: "Uncooked Chicken Samosa", ar: "دجاج سمبوسة غير مقلية", price: 20, img: "/products/11034.webp", cat: "bakery", sub: "frozen" },
  { id: 200102, en: "Uncooked Shami Kebab", ar: "كباب شامي غير مقلية", price: 30, img: "/products/10650.webp", cat: "bakery", sub: "frozen" },
  { id: 200103, en: "Uncooked Potato Samosa", ar: "سمبوسة بطاطس غير مقلية", price: 10, img: "/products/10648.jpg", cat: "bakery", sub: "frozen" },
  { id: 200104, en: "Khoya", ar: "زبدة الحليب", price: 15, img: "/products/10643.jpg", cat: "bakery", sub: "mixed-items", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }, { label: "QAR 60", price: 60 }] },
  { id: 200105, en: "Pheni", ar: "فيني", price: 28, img: "/products/10644.jpg", cat: "bakery", sub: "mixed-items", variations: [{ label: "QAR 28", price: 28 }, { label: "QAR 55", price: 55 }] },
  { id: 200106, en: "Nimco Mix", ar: "متاي مزج", price: 8, img: "/products/11021.jpg", cat: "bakery", sub: "mixed-items", variations: [{ label: "QAR 8", price: 8 }, { label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200107, en: "Phulki (Bondi)", ar: "فول (بوندي)", price: 17, img: "/products/10645.webp", cat: "bakery", sub: "mixed-items" },
  { id: 200108, en: "Fruit Bun", ar: "خبز فواكه", price: 2, img: "/products/10666.jpg", cat: "bakery", sub: "mixed-items" },
  { id: 200109, en: "Cream Bun", ar: "خبز كريم", price: 2, img: "/products/10667.jpg", cat: "bakery", sub: "mixed-items" },
  { id: 200110, en: "Tea Cake", ar: "كيك شاي صغير", price: 7, img: "/products/10668.jpg", cat: "bakery", sub: "mixed-items" },
  { id: 200111, en: "Fruit Cake", ar: "فواكه كيك صغير", price: 7, img: "/products/10669.jpg", cat: "bakery", sub: "mixed-items" },
  { id: 200112, en: "Cream Roll", ar: "كريم رول", price: 5, img: "/products/10670.jpg", cat: "bakery", sub: "mixed-items" },
  { id: 200113, en: "Badaam Barfi", ar: "في اللوز بار", price: 70, img: "/products/10687.jpg", cat: "sweets", sub: "barfi" },
  { id: 200114, en: "Pista Barfi Roll", ar: "في رول بار", price: 70, img: "/products/10689.webp", cat: "sweets", sub: "barfi" },
  { id: 200115, en: "Barfi Special", ar: "في بار", price: 70, img: "/products/11087.jpg", cat: "sweets", sub: "barfi" },
  { id: 200116, en: "Goond Barfi", ar: "في شوكولاتة بار", price: 70, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "barfi" },
  { id: 200117, en: "Dil Barfi", ar: "في القلب بار", price: 70, img: "/products/10692.jpg", cat: "sweets", sub: "barfi" },
  { id: 200118, en: "Kalakand", ar: "كالاكاند", price: 70, img: "/products/10693.jpg", cat: "sweets", sub: "barfi" },
  { id: 200119, en: "Pineapple Cake", ar: "أناناس كيك", price: 100, img: "/products/10694.jpg", cat: "cakes", sub: "cakes" },
  { id: 200120, en: "Black Forest Cake", ar: "بلاك فورست كيك", price: 100, img: "/products/10702.jpg", cat: "cakes", sub: "cakes" },
  { id: 200121, en: "Chocolate Cake", ar: "شوكولاتة كيك", price: 100, img: "/products/10703.jpg", cat: "cakes", sub: "cakes" },
  { id: 200122, en: "2 in 1 Cake", ar: "في 1 كيك 2", price: 100, img: "/products/10704.jpg", cat: "cakes", sub: "cakes" },
  { id: 200123, en: "Fresh Fruit Cake", ar: "طازج فواكه كيك", price: 100, img: "/products/10763.jpg", cat: "cakes", sub: "cakes" },
  { id: 200124, en: "Lotus Cake", ar: "لوتس كيك", price: 120, img: "/products/10766.jpg", cat: "cakes", sub: "cakes" },
  { id: 200125, en: "Kitkat Cake", ar: "كت كات كيك", price: 120, img: "/products/10769.webp", cat: "cakes", sub: "cakes" },
  { id: 200126, en: "Maltesers Cake", ar: "مالتيزرز كيك", price: 120, img: "/products/10771.jpg", cat: "cakes", sub: "cakes" },
  { id: 200127, en: "Raffaello Cake", ar: "رافايلو كيك", price: 120, img: "/products/10774.jpg", cat: "cakes", sub: "cakes" },
  { id: 200128, en: "Rich Chocolate Cake", ar: "كيك الشوكولاتة الداكنة", price: 120, img: "/products/10776.jpg", cat: "cakes", sub: "cakes" },
  { id: 200129, en: "Ferrero Cake", ar: "فيرو كيك", price: 120, img: "/products/11114.jpg", cat: "cakes", sub: "cakes" },
  { id: 200130, en: "Red Velvet Cake", ar: "ريد فيلفيت كيك", price: 120, img: "/products/11117.jpg", cat: "cakes", sub: "cakes" },
  { id: 200131, en: "Irish Coffee Cake", ar: "القهوة الإيرلندية كيك", price: 120, img: "/products/11120.jpg", cat: "cakes", sub: "cakes" },
  { id: 200132, en: "Gulab Jamun Milk Cake", ar: "جلاب جامون كيك", price: 100, img: "/products/11123.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200133, en: "Ras Malai Milk Cake", ar: "لاي كيك راس", price: 120, img: "/products/11126.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200134, en: "Caramel Crunch Cake", ar: "كراميل أزمة كعك", price: 120, img: "/products/11129.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200135, en: "Pistachio Cake", ar: "فستق كيك", price: 120, img: "/products/11133.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200136, en: "Honey Cake", ar: "عسل كيك", price: 120, img: "/products/11136.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200137, en: "Signature Chocolate Cake", ar: "مميز شوكولاتة كيك", price: 140, img: "/products/11140.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200138, en: "Birthday Cake", ar: "كعكة عيد ميلاد", price: 140, img: "/products/11143.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200139, en: "XOXO Cake", ar: "كيكة اكس او اكس او", price: 140, img: "/products/11147.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200140, en: "Anniversary Cake", ar: "كعكة الذكرى", price: 160, img: "/products/11150.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200141, en: "Umrah Cake", ar: "كيكة العمرة", price: 140, img: "/products/11153.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200142, en: "German Chocolate Cake", ar: "كعكة الشوكولاتة الألمانية", price: 140, img: "/products/11156.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200143, en: "Love Cake", ar: "كعكة الحب", price: 160, img: "/products/11159.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200144, en: "Congratulations Cake", ar: "كعكة مبروك", price: 160, img: "/products/11162.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200145, en: "Graduation Cake", ar: "كيكة التخرج", price: 140, img: "/products/11166.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200146, en: "Cheese Cake", ar: "كعكة الجبنة", price: 140, img: "/products/11523.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200147, en: "Mother’s Day Cake", ar: "كعكة عيد الأم", price: 35, img: "/products/11169.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200148, en: "Dry Nut Cake", ar: "جاف كيك", price: 6, img: "/products/11172.jpg", cat: "cakes", sub: "signature-cakes" },
  { id: 200149, en: "Pineapple Cake Piece", ar: "أناناس كيك", price: 6, img: "/products/11175.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200150, en: "Black Forest Cake Piece", ar: "بلاك فورست كيك", price: 10, img: "/products/11178.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200151, en: "Lotus Cake Piece", ar: "لوتس كيك", price: 10, img: "/products/11181.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200152, en: "Signature Chocolate Cake Piece", ar: "مميز شوكولاتة كيك", price: 10, img: "/products/11184.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200153, en: "Pistachio Cake Piece", ar: "فستق كيك", price: 10, img: "/products/11187.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200154, en: "Red Velvet Cake Piece", ar: "ريد فيلفيت كيك", price: 10, img: "/products/11190.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200155, en: "Raffaello Cake Piece", ar: "رافايلو كيك", price: 10, img: "/products/11193.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200156, en: "Rich Chocolate Cake Piece", ar: "كيك الشوكولاتة الداكنة", price: 10, img: "/products/11196.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200157, en: "Caramel Crunch Cake Piece", ar: "كراميل أزمة كعك", price: 10, img: "/products/11199.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200158, en: "Cream Puff", ar: "كريم باف", price: 6, img: "/products/11202.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200159, en: "Cheese Cake Slice", ar: "كعكة الجبن", price: 5, img: "/images/cakes.jpg", cat: "cakes", sub: "cake-pieces-pastry" },
  { id: 200160, en: "Assorted Pastry Box", ar: "بوكس حلويات منوعة", price: 12, img: "/products/11555.jpg", cat: "cakes", sub: "cake-pieces-pastry", variations: [{ label: "QAR 12", price: 12 }, { label: "QAR 50", price: 50 }, { label: "QAR 100", price: 100 }] },
  { id: 200161, en: "Chana Papri Chaat", ar: "شانا بابري شات", price: 10, img: "/products/11205.jpg", cat: "chaat-snacks", sub: "chaat-items" },
  { id: 200162, en: "Dahi Papri", ar: "دهي بابري", price: 12, img: "/products/11223.jpg", cat: "chaat-snacks", sub: "chaat-items" },
  { id: 200163, en: "Dahi Puri", ar: "دهي بوري", price: 12, img: "/products/11211.jpg", cat: "chaat-snacks", sub: "chaat-items" },
  { id: 200164, en: "Pani Puri", ar: "باني بوري", price: 10, img: "/products/11214.jpg", cat: "chaat-snacks", sub: "chaat-items" },
  { id: 200165, en: "Samosa Chaat (Spicy/Sweet)", ar: "شات سمبوسة (حار / حلو)", price: 12, img: "/products/11217.jpg", cat: "chaat-snacks", sub: "chaat-items" },
  { id: 200166, en: "Papri", ar: "بابري", price: 5, img: "/products/11223.jpg", cat: "chaat-snacks", sub: "chaat-items" },
  { id: 200167, en: "Mix Sweets (Regular)", ar: "حلويات مشكلة (عادية)", price: 15, img: "/products/11242.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200168, en: "Jalebi", ar: "جليبي", price: 15, img: "/products/11246.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200169, en: "Ladoo", ar: "لدو", price: 15, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200170, en: "Shakar", ar: "شكر", price: 15, img: "/products/11252.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200171, en: "Unni Khumay", ar: "أوني خمياي", price: 15, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200172, en: "Balu Shahi", ar: "بالو شاهي", price: 15, img: "/products/11256.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200173, en: "Lacha Patta", ar: "لاشا باتا", price: 15, img: "/products/11259.jpg", cat: "sweets", sub: "sweets", variations: [{ label: "QAR 15", price: 15 }, { label: "QAR 30", price: 30 }] },
  { id: 200174, en: "Gajar Halwa", ar: "غاجر حلوى", price: 60, img: "/products/11462.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200175, en: "Ras Malai", ar: "راس مالاي", price: 60, img: "/products/11468.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200176, en: "Kheer (Rice Pudding)", ar: "كير (بودينغ الأرز)", price: 40, img: "/products/11471.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200177, en: "Muff Kulfa", ar: "ماف كلفا", price: 60, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200178, en: "Khopra Halwa", ar: "حلوى جوز الهند", price: 60, img: "/products/11434.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200179, en: "Moti Choor Ladoo", ar: "موتي تشور لدو", price: 60, img: "/products/11373.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200180, en: "Dhoodh Jalebi", ar: "دودھ جليبي", price: 60, img: "/products/11246.jpg", cat: "sweets", sub: "sweet-snacks" },
  { id: 200181, en: "Aloo Chips", ar: "بطاطس مقرمشة", price: 3, img: "/products/11265.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200182, en: "Aloo Gol Gappa", ar: "ألو غول غابا", price: 10, img: "/products/11268.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200183, en: "Chicken Spring Roll", ar: "سبرنج رول دجاج", price: 10, img: "/products/11310.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200184, en: "Chili Fry", ar: "تشيلي فراي", price: 15, img: "/images/chaat.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200185, en: "Kachori (Onion/Chicken)", ar: "كاتشوري (بصل / دجاج)", price: 6, img: "/products/11280.webp", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200186, en: "Masala Panay", ar: "ماسالا باناي", price: 10, img: "/images/chaat.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200187, en: "Pakora", ar: "باكورا", price: 5, img: "/products/11289.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200188, en: "Kheema Samosa", ar: "سمبوسة كيما", price: 5, img: "/products/11298.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200189, en: "Paneer Samosa", ar: "سمبوسة بانير", price: 5, img: "/products/11298.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200190, en: "Aloo Samosa", ar: "سمبوسة بطاطس", price: 5, img: "/products/11292.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200191, en: "Chicken Patties", ar: "فطائر دجاج", price: 5, img: "/products/11307.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200192, en: "Beef Chicken Sandwich", ar: "ساندويتش دجاج أو لحم", price: 6, img: "/products/11316.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200193, en: "Paratha Roll", ar: "براثا رول", price: 6, img: "/images/chaat.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200194, en: "Shami Kebab", ar: "شامي كباب", price: 5, img: "/products/11304.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200195, en: "Egg Club Sandwich", ar: "ساندويتش كلوب بالبيض", price: 6, img: "/products/11334.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200196, en: "Chicken Burger", ar: "برجر دجاج", price: 6, img: "/products/11349.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200197, en: "Beef Burger", ar: "برجر لحم", price: 6, img: "/images/chaat.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200198, en: "Bread Pakora", ar: "بريد باكورا", price: 5, img: "/products/11346.jpg", cat: "chaat-snacks", sub: "savory-snacks" },
  { id: 200199, en: "Halwa Puri Nashta", ar: "حلوا بوري ناشتا", price: 12, img: "/products/11226.jpg", cat: "chaat-snacks", sub: "desi-breakfast" },
  { id: 200200, en: "Puri Halwa", ar: "بوري حلوا", price: 12, img: "/products/11230.jpg", cat: "chaat-snacks", sub: "desi-breakfast" },
  { id: 200201, en: "Sufi Halwa", ar: "صوفي حلوا", price: 12, img: "/products/11449.jpg", cat: "chaat-snacks", sub: "desi-breakfast" },
  { id: 200202, en: "Shahi Halwa", ar: "شاهي حلوا", price: 12, img: "/products/11452.jpg", cat: "chaat-snacks", sub: "desi-breakfast" },
  { id: 200203, en: "Mutton Nihari", ar: "نهاري لحم", price: 16, img: "/products/11739.jpg", cat: "chaat-snacks", sub: "desi-breakfast" },
  { id: 200204, en: "Kashmiri Pink Tea", ar: "شاي كشميري وردي", price: 5, img: "/images/chaat.jpg", cat: "chaat-snacks", sub: "desi-breakfast" },
  { id: 200205, en: "Special Sweets Mix", ar: "حلويات خاصة مشكلة", price: 60, img: "/products/11352.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200206, en: "Besan Patisa", ar: "بيسان باتيسا", price: 60, img: "/products/11355.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200207, en: "Chana Mithai", ar: "شانا ميتاي", price: 60, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200208, en: "Gulab Jamun", ar: "جلاب جامون", price: 60, img: "/products/11364.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200209, en: "Mango Gulab Jamun", ar: "مانجو جلاب جامون", price: 60, img: "/products/11364.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200210, en: "Kala Jamun", ar: "كالا جامون", price: 60, img: "/products/11367.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200211, en: "Ras Malai", ar: "راس مالاي", price: 60, img: "/products/11468.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200212, en: "Khopra Barfi", ar: "بارفي جوز الهند", price: 60, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200213, en: "Chocolate Barfi", ar: "بارفي شوكولاتة", price: 60, img: "/products/10691.webp", cat: "sweets", sub: "special-sweet" },
  { id: 200214, en: "Pista Barfi", ar: "بارفي فستق", price: 60, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200215, en: "White Barfi", ar: "بارفي أبيض", price: 60, img: "/images/hero-sweets.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200216, en: "Coconut Halwa", ar: "حلوى جوز الهند", price: 60, img: "/products/11428.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200217, en: "Dry Fruit Halwa", ar: "حلوى الفواكه الجافة", price: 60, img: "/products/11431.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200218, en: "Mutanj Sohaan Halwa", ar: "موتانج سهان حلوى", price: 60, img: "/products/11459.jpg", cat: "sweets", sub: "special-sweet" },
  { id: 200219, en: "Lassi", ar: "لسي", price: 6, img: "/products/11585.jpg", cat: "drinks", sub: "lassi" },
  { id: 200220, en: "Special Khoya Lassi", ar: "لسي خويا خاص", price: 10, img: "/products/10643.jpg", cat: "drinks", sub: "lassi" },
];
